### ISSUE TITLE
Loading issue with LL-HLS

### ISSUE THREAD

**Issue by lyvecom** [muxinc/videojs-mux-kit#52] opened 2021-09-27 17:28 UTC
After using the Mux Video.js kit and enabling LL-HLS as per this [blog post](https://mux.com/blog/introducing-low-latency-live-streaming/), we're experiencing extremely slow initial load times when viewing the stream. This issue is especially evident on desktop (Chrome/Safari), where a stream would take 15-30 seconds on first time load to view the stream.

**Comment by dylanjha** [comment] 2021-09-27 21:01
Hi @lyvecom 

I *think* the bug you're running into is [this one with hls.js](https://github.com/video-dev/hls.js/issues/4302)

We have that fixed merged, but a new release has not gone out yet. We're working with the Hls.js maintainers to get that shipped in the next release (likely 1.0.11).

After that goes out it would be good to give that shot and see if it resolves your issue. Is it easily reproducible for your or is it more intermittent? If it's easily reproducible and you are able to provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) then we are happy to take a look and make sure that the merged patch does in-fact resolve this for you.

**Comment by mmcc** [comment] 2021-12-06 00:43
Hi there, #61 included a minor version bump for hls.js, so this _should_ be fixed now. Could you let us know if you still see issues?

**Comment by lyvecom** [comment] 2021-12-06 06:18
Hi there, we actually manually compiled the Mux Kit which fixed the issue for us. 

Thanks for taking a look at this!

-M

**Comment by gkatsev** [comment] 2022-08-25 19:49
I believe this has since been fixed.

Let us know if it's still an issue.

**Closed by gkatsev** 2022-08-25 19:49 UTC
